---
- name: Install NVIDIA Container Toolkit
  hosts: all
  become: yes
  tasks:

    - name: install nvidia drivers
      command: ubuntu-drivers install nvidia:535
      ignore_errors: yes

    - name: Add NVIDIA Container Toolkit's GPG key
      shell: |
        curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

    - name: Add NVIDIA Container Toolkit repository
      shell: |
        curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
        sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
        tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

    - name: Enable experimental features in NVIDIA Container Toolkit repository
      replace:
        path: /etc/apt/sources.list.d/nvidia-container-toolkit.list
        regexp: '^#(.*experimental.*)$'
        replace: '#\1'

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install NVIDIA Container Toolkit
      apt:
        name: nvidia-container-toolkit
        state: present

    - name: Configure NVIDIA Container Toolkit for Docker runtime
      shell: |
        nvidia-ctk runtime configure -runtime=docker

    - name: Restart Docker service
      service:
        name: docker
        state: restarted


    - name: Execute nvidia-smi command
      local_action: command nvidia-smi
      register: gpu_info
      ignore_errors: yes


    - name: Display GPU information
      debug:
        msg: "{{ item }}"
      loop: "{{ gpu_info.stdout_lines }}"
      ignore_errors: yes

