- hosts: all
  become: yes
  tasks:
     - name: Update and upgrade apt packages
       become: yes
       ignore_errors: yes
       failed_when: "'FAILED' in command_result.stderr"
       apt:
         upgrade: yes
         update_cache: yes
         cache_valid_time: 86400 #One day


      - name: Make sure we have a 'workers' group
        group:
           name: workers
           state: present

      
      - name: Allow 'workers' group to have passwordless sudo
         lineinfile:
           dest: /etc/sudoers
           state: present
           regexp: '^%workers'
           line: '%workers ALL=(ALL) NOPASSWD: ALL'
           validate: 'visudo -cf %s'


       - name: Add sudoers users to workers group
         user:
           name: ubuntu
           groups: workers
           append: yes
           state: present
           createhome: yes
           shell: /bin/bash
        
       - name: Create necessary folders
         file: 
           path: "{{ item }}"
           recurse: yes
           state: directory
           with_items:
                 - /home/ubuntu/.ssh/



       - name: Copy Secured SSHD Configuration
         copy: src=sshd_config_secured dest=/etc/ssh/sshd_config owner=ubuntu group=ubuntu mode=0644


      - name: Disable IPv6
        sysctl:
          name: "{{ item }}"
         value: '1'
         sysctl_set: yes
         state: present
       with_items:
         - net.ipv6.conf.all.disable_ipv6
         - net.ipv6.conf.default.disable_ipv6
         - net.ipv6.conf.lo.disable_ipv6

     - name: SSHD Restart
       service: name=sshd state=restarted enabled=yes
         #sudo: yes

     - name: Copy keys and profiles
       copy:
         src: "{{ item.src }}"
         dest: "{{ item.dest }}"
         owner: ubuntu
         group: ubuntu
         mode: 0400
       with_items:
         - { src: 'authorized_keys', dest: '/home/ubuntu/.ssh/authorized_keys' }
